### ISSUE TITLE
Checklist before deploy

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp-site#1]
- [x] apt upgrade
- [x] Login using magic key on /login
  - [x] Translate the "forward" option and redirect
- [x] List goldfiles on download page if logged in
  - [x] Automatically generate file lists
  - [x] Link to buy gold if you're not logged in
  - [x] Sort the gold files in with the others
  - [x] Add file serving of gold files using the API
- [x] Do a test deploy on new.ppsspp.org and set up all necessary proxies and redirects
- [x] Implement "Change password"
- [x] Implement "Recover password"
- [x] Add new Buy Gold page
  - [x] Add new Thank you page
    - [x] Add live update on thankyou page
  - [x] Test it, and make sure the bought state looks good and makes sense
  - [x] Polish
- [x] Redesign front page
- [x] Add videos to screenshots&videos
- [x] Add nginx redirects for all the old pages
- [x] Try to test the ads somehow
- [x] Do some kind of environment variable setup, so we can have release and debug deploy scripts
- [x] Document the deployment process
- [x] Reformat code (tabs)

Actual deploy:

- [x] Deploy central server to main, make sure it still works.
- [x] Modify the nginx config

Post deploy:

- [x] Add redirects from old gold pages to new ones
  - [x] Set up redirect for the above from "loginbykey" in nginx

Redirect list:

## Redirections on main site

screenshots.html -> /media
downloads.html -> /download
guides.html -> /docs
privacy.html -> /privacy
contact.html -> /contact
guide_androidfiles.html -> /docs/androidfiles
guide_storage.html -> /docs/androidstorage
guide_hardware.html -> /docs/getting-started/recommended-hardware
getgames.html -> /docs/getgames
gethomebrew.html -> /docs/getting-started/get-homebrew-and-demos
devbuilds.html -> /downloads
development.html -> /docs/development/getting-started
at3plusdecoder.html -> /

# Redirections on central

whygold -> /docs/reference/whygold
loginbykey -> /login
buygold -> /buygold
profile -> /login

forgotpassword ->

**Comment by Gamemulatorer** [comment]
Can you also add in the site about the settings functionality like this.

Drastic for example
![Screenshot_20230218_092338](https://user-images.githubusercontent.com/37603562/219824153-fd5ccd33-4067-464b-aabc-2c9819f9e30d.jpg)

See also https://github.com/hrydgard/ppsspp/issues/16980
